backend:
  name: github
  repo: bino98/this-blog-is-about
  branch: master
 
publish_mode: editorial_workflow
 
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
 
collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text", required: false}
      - {label: "LinkTitle", name: "linktitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", require: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Width", name: "width", widget: "number", required: false}
      - {label: "Category", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "AuthorAvatar", name: "authorAvatar", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
